const PERMISSIONS = {
  // Member Management
  INVITE_MEMBER: ['ADMIN', 'PROJECT_MANAGER'],
  REMOVE_MEMBER: ['ADMIN', 'PROJECT_MANAGER'],
  CHANGE_MEMBER_ROLE: ['ADMIN'],
  CHANGE_MEMBER_STATUS: ['ADMIN'],

  // Workspace Management
  UPDATE_WORKSPACE: ['ADMIN', 'PROJECT_MANAGER'],
  DELETE_WORKSPACE: ['ADMIN'],

  // Goal Management
  CREATE_GOAL: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR', 'MEMBER'],
  UPDATE_ANY_GOAL: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR'],
  UPDATE_OWN_GOAL: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR', 'MEMBER'],
  DELETE_GOAL: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR'],

  // Announcement Management
  CREATE_ANNOUNCEMENT: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR'],
  PIN_ANNOUNCEMENT: ['ADMIN'],
  DELETE_ANNOUNCEMENT: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR'],
  REACT_ANNOUNCEMENT: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR', 'MEMBER'],
  COMMENT_ANNOUNCEMENT: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR', 'MEMBER'],

  // Action Management
  CREATE_ACTION: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR', 'MEMBER'],
  UPDATE_OWN_ACTION: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR', 'MEMBER'],
  UPDATE_ANY_ACTION: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR'],
  DELETE_ACTION: ['ADMIN', 'PROJECT_MANAGER', 'MODERATOR'],

  // Data & Audit
  EXPORT_DATA: ['ADMIN'],
  VIEW_AUDIT_LOG: ['ADMIN'],
}

function can(role, permission) {
  return PERMISSIONS[permission]?.includes(role) ?? false
}

module.exports = {
  PERMISSIONS,
  can,
}
