// Mock data for development - replace with real API calls later

export const mockGoals = [
  {
    id: 'goal-1',
    title: 'Q1 Revenue Target',
    description: 'Increase revenue by 25% through new partnerships and market expansion',
    status: 'ON_TRACK',
    progress: 65,
    dueDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    owner: { id: 'user-1', name: 'Sarah Johnson', avatar: null },
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'goal-2',
    title: 'Product Launch v2.0',
    description: 'Launch new product features including AI integration and analytics',
    status: 'ON_TRACK',
    progress: 40,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    owner: { id: 'user-2', name: 'Mike Chen', avatar: null },
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'goal-3',
    title: 'Customer Satisfaction Score',
    description: 'Achieve 95% customer satisfaction rating across all products',
    status: 'AT_RISK',
    progress: 78,
    dueDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    owner: { id: 'user-3', name: 'Emma Davis', avatar: null },
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'goal-4',
    title: 'Market Research',
    description: 'Complete comprehensive market analysis and competitor benchmarking',
    status: 'COMPLETED',
    progress: 100,
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    owner: { id: 'user-1', name: 'Sarah Johnson', avatar: null },
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockActions = [
  {
    id: 'action-1',
    title: 'Review Q1 metrics and KPIs',
    status: 'todo',
    assignee: { id: 'user-1', name: 'Sarah Johnson' },
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    goalId: 'goal-1',
    priority: 'high',
    description: 'Analyze performance metrics and identify trends',
  },
  {
    id: 'action-2',
    title: 'Schedule stakeholder meeting',
    status: 'in_progress',
    assignee: { id: 'user-2', name: 'Mike Chen' },
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    goalId: 'goal-1',
    priority: 'high',
    description: 'Set up meeting with key stakeholders to discuss Q1 results',
  },
  {
    id: 'action-3',
    title: 'Prepare demo materials',
    status: 'todo',
    assignee: { id: 'user-3', name: 'Emma Davis' },
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    goalId: 'goal-2',
    priority: 'medium',
    description: 'Create presentation slides and product demo',
  },
  {
    id: 'action-4',
    title: 'Complete API documentation',
    status: 'completed',
    assignee: { id: 'user-1', name: 'Sarah Johnson' },
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    goalId: 'goal-2',
    priority: 'high',
    description: 'Document all new API endpoints and features',
  },
  {
    id: 'action-5',
    title: 'Conduct user testing sessions',
    status: 'in_progress',
    assignee: { id: 'user-2', name: 'Mike Chen' },
    dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    goalId: 'goal-3',
    priority: 'medium',
    description: 'Gather feedback from 20+ users on new features',
  },
]

export const mockMembers = [
  {
    id: 'user-1',
    userId: 'user-1',
    user: {
      id: 'user-1',
      name: 'Sarah Johnson',
      email: 'sarah@example.com',
      avatar: null,
    },
    role: 'ADMIN',
    isActive: true,
    status: 'active',
    joinedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-2',
    userId: 'user-2',
    user: {
      id: 'user-2',
      name: 'Mike Chen',
      email: 'mike@example.com',
      avatar: null,
    },
    role: 'MEMBER',
    isActive: true,
    status: 'active',
    joinedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-3',
    userId: 'user-3',
    user: {
      id: 'user-3',
      name: 'Emma Davis',
      email: 'emma@example.com',
      avatar: null,
    },
    role: 'MEMBER',
    isActive: true,
    status: 'active',
    joinedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-4',
    userId: 'user-4',
    user: {
      id: 'user-4',
      name: 'Alex Rodriguez',
      email: 'alex@example.com',
      avatar: null,
    },
    role: 'MEMBER',
    isActive: false,
    status: 'inactive',
    joinedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockAnnouncements = [
  {
    id: 'announce-1',
    title: 'Welcome to FredoCloud Team Hub',
    content: 'Welcome to our collaborative workspace! This is where the entire team comes together to track goals, manage actions, and stay connected. Feel free to explore all the features and don\'t hesitate to reach out with any questions.',
    author: { id: 'user-1', name: 'Sarah Johnson' },
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: true,
    reactions: [
      { emoji: '👋', userId: 'user-2', user: { name: 'Mike Chen' } },
      { emoji: '👋', userId: 'user-3', user: { name: 'Emma Davis' } },
    ],
    commentCount: 3,
  },
  {
    id: 'announce-2',
    title: 'Q1 Results are In!',
    content: 'Excited to share that we\'ve exceeded our Q1 revenue targets by 32%! This was a phenomenal effort from the entire team. Check out the Analytics section for detailed breakdowns and trends. Great work everyone!',
    author: { id: 'user-1', name: 'Sarah Johnson' },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    reactions: [
      { emoji: '🎉', userId: 'user-2', user: { name: 'Mike Chen' } },
      { emoji: '🎉', userId: 'user-3', user: { name: 'Emma Davis' } },
      { emoji: '🚀', userId: 'user-1', user: { name: 'Sarah Johnson' } },
    ],
    commentCount: 8,
  },
  {
    id: 'announce-3',
    title: 'Team Meeting Schedule Updated',
    content: 'Please note that our weekly team sync has been moved to Thursdays at 2 PM EST. All team members should have updated calendar invites. If you have any conflicts, please reach out to HR.',
    author: { id: 'user-2', name: 'Mike Chen' },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    reactions: [
      { emoji: '👍', userId: 'user-3', user: { name: 'Emma Davis' } },
    ],
    commentCount: 2,
  },
]

export const mockActivity = [
  {
    id: 'activity-1',
    actor: { id: 'user-1', name: 'Sarah Johnson', avatarUrl: null },
    action: 'CREATE',
    entityType: 'Goal',
    entityId: 'goal-1',
    entityName: 'Q1 Revenue Target',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-2',
    actor: { id: 'user-2', name: 'Mike Chen', avatarUrl: null },
    action: 'CREATE',
    entityType: 'ActionItem',
    entityId: 'action-2',
    entityName: 'Schedule stakeholder meeting',
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-3',
    actor: { id: 'user-1', name: 'Sarah Johnson', avatarUrl: null },
    action: 'UPDATE',
    entityType: 'Goal',
    entityId: 'goal-1',
    entityName: 'Q1 Revenue Target',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-4',
    actor: { id: 'user-3', name: 'Emma Davis', avatarUrl: null },
    action: 'CREATE',
    entityType: 'Announcement',
    entityId: 'announce-2',
    entityName: 'Q1 Results are In!',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-5',
    actor: { id: 'user-2', name: 'Mike Chen', avatarUrl: null },
    action: 'UPDATE',
    entityType: 'ActionItem',
    entityId: 'action-2',
    entityName: 'Schedule stakeholder meeting',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-6',
    actor: { id: 'user-1', name: 'Sarah Johnson', avatarUrl: null },
    action: 'CREATE',
    entityType: 'ActionItem',
    entityId: 'action-5',
    entityName: 'Conduct user testing sessions',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockAnalytics = {
  goalsCompleted: 1,
  totalGoals: 4,
  actionsCompleted: 1,
  totalActions: 5,
  teamMembers: 4,
  overallProgress: 56,
}

export const mockTrash = {
  goals: [
    {
      id: 'trash-goal-1',
      title: 'Old Q4 Revenue Target',
      description: 'Previous quarter revenue goal - no longer needed',
      status: 'ON_TRACK',
      progress: 45,
      dueDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
      deletedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      owner: { id: 'user-1', name: 'Sarah Johnson', avatar: null },
    },
  ],
  actions: [
    {
      id: 'trash-action-1',
      title: 'Deprecated API integration',
      status: 'todo',
      assignee: { id: 'user-2', name: 'Mike Chen' },
      dueDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
      goalId: null,
      priority: 'medium',
      description: 'No longer needed - replaced with new API',
      deletedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  announcements: [
    {
      id: 'trash-announce-1',
      title: 'Old System Maintenance Notice',
      content: 'This was posted during the old system migration.',
      author: { id: 'user-3', name: 'Emma Davis' },
      createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
      isPinned: false,
      reactions: [],
      deletedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
}
